### ISSUE TITLE
update

### ISSUE THREAD

**Issue by TeaqariaWTF** [adrianmmiller/Dnscrypt-Proxy-Maintenance-Script-Android-SH-#1]
Hi ,

Will this project continue to be updated?

**Comment by adrianmmiller** [comment]
Not sure what needs updating....

I created a rough version that was good enough for personal use, was then asked to make it more polished for possible inclusion in the magisk module by quindecim who then completely ignored it...so i havent worried about it since. Im, not much into people wasting my time. the basic functions should realyl ever change....

**Comment by TeaqariaWTF** [comment]
I didn't mean to offend, I apologize.

I just wondered if the project will continue to be supported in the future.

Have a good day

**Comment by adrianmmiller** [comment]
no, you didnt in any way offend me :) . 

i was just explaining the 2 reasons why its probably not actively updated, it shouldnt really need it is the main reason. if you do find a problem, for sure let me know
